- name: Define php_packages.
  set_fact:
    php_packages: "{{ __php_packages | list }}"
  when: php_packages is not defined

- name: Ensure PHP packages are installed.
  apt:
    name: "{{ item }}"
    state: installed
  with_items: php_packages
  notify: restart webserver

- name: Ensure configuration directories exist.
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ php_conf_path }}"
    - "{{ php_extension_conf_path }}"

- name: Place PHP configuration file in place.
  template:
    src: php.ini.j2
    dest: "{{ php_conf_path }}/php.ini"
    owner: root
    group: root
    mode: 0644
  notify: restart webserver

- name: Place APC configuration file in place.
  template:
    src: apc.ini.j2
    dest: "{{ php_extension_conf_path }}/{{ php_apc_conf_filename }}"
    owner: root
    group: root
    mode: 0644
  when: php_enable_apc
  notify: restart webserver

- name: Ensure php-fpm is started and enabled at boot (if configured).
  service:
    name: php-fpm
    state: started
    enabled: yes
  when: php_enable_php_fpm

- name: Install composer
  shell:
    curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin/ --filename=composer
    creates=/usr/local/bin/composer
